# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}/"
  name: tensorboard
  log_graph: False
  default_hp_metric: True
  prefix: ""
